# Generated by Django 5.2.4 on 2025-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_gpa_customuser_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
