# Generated by Django 5.2.4 on 2025-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_university_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='fee',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
