# Generated by Django 5.2.4 on 2025-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_university_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
