# Generated by Django 5.2.4 on 2025-09-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_university_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='fee',
        ),
    ]
