# Generated by Django 5.2.4 on 2025-09-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
